{
 "title": "pendulum-dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "simulation_time",
   "type": "bargauge",
   "gridPos": { "x": 15, "y": 0, "w": 3, "h": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "simulation_time_second" }
   ]
  },
  {
   "title": "pendulum_period",
   "type": "histogram",
   "gridPos": { "x": 0, "y": 5, "w": 15, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pendulum_period_second" }
   ]
  },
  {
   "title": "pendulum_energy",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 15, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "J" } },
   "targets": [
    { "expr": "pendulum_energy_joule" },
    { "expr": "pendulum_energy_target_joule" }
   ]
  }
 ]
}