{
 "title": "pendulum-dashboard",
 "refresh": "1s",
 "panels": [
  {
   "title": "simulation_time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "simulation_time" }
   ]
  },
  {
   "title": "pendulum_energy",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pendulum_energy" }
   ]
  },
  {
   "title": "pendulum_period",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pendulum_period" }
   ]
  }
 ]
}